name: Build Flipper Application Package (.fap)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-fap:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Build your .fap with uFBT (this auto‐installs the SDK & runs `ufbt build`)
      - name: Build .fap with uFBT
        id: ufbt_build
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        with:
          sdk-channel: release
          # (If you want to skip the lint step, add `task: build` here.)

      # 3) Upload the .fap as a downloadable artifact
      - name: Upload .fap artifact
        if: ${{ steps.ufbt_build.outputs.fap-artifacts != '' }}
        uses: actions/upload-artifact@v2
        with:
          name: orthodox_prayers_fap
          path: ${{ steps.ufbt_build.outputs.fap-artifacts }}
